version=2
global.lookup.bucket=global-lookup
global.payments.host=127.0.0.1
global.payments.port=80
global.payments.scheme=http
global.return_workflow.targetId=flipkart


global.elixir.issueConfig.2111.similarIssues=2111,3267
global.elixir.issueConfig.3267.similarIssues=2111,3267

global.elixir.issueConfig.3234.similarIssues=2112,3234
global.elixir.issueConfig.2112.similarIssues=2112,3234

